%%
%%%Parameters for Data tab%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
startingOffset='0.4';
endingOffset ='0.6';
%%
%%%%%Parameters for Features Extraction & Reduction Tab %%%%%%%%%%%%%%%%%%%
classes={'All','Customize'};
%classes={'Rock,Paper,Scissor','Rock,Paper','Rock,Scissor','Paper,Scissor'};

featuresExtraction = {'SortedSpikes','UnsortedSpikes','LocalFieldPotential(LFP)',... 
                'ConvolutionalStackedAuto-Encoders'};



featuresReduction = {'Principal Componenet Analysis(PCA)',...
                'Independent Component Analysis(ICA)',...
                'Restricted Boltzman Machine(RBM)', ...
                'Auto-Encoders', ....
                'None'};
  
            
 decoAlgoC = {'NeuralNetworksC','LinearRegressionC','LogisticRegressionC', ...
                'SupportVectorMachineC','RandomForestC','K-NearestNeighboursC', ...
                'LinearDiscriminativeClassifierC', ...
                };
            
decoAlgoR = {'NeuralNetworksR','LinearRegressionR','LogisticRegressionR','RecurrentNeuralNetworks' ...
                'KalmanFilters', ...
                };     
            
            