classdef GUIBCIFW2 < handle
    properties
        %%
        controller %##Object for controller class
        %%
        hFig %Parent(mainCanvas)
        %%
        hTabGpBCI %tabGroup: object for BCI frame work will contain
        %Our BCI will contain three main tab
        %1)
        hTabData %tab: data
        %2)
        hTabFeatExtRed%tab: Features extraction and reduction
        %3)
        hTabDecoder% tab : Decoder
        
        hTabDecoderTestOffline %tab :to check the performance of decoder offline
        
        %Most of ui components for this gui are object of 'uicontrol' class
        %only few are taken outside of that.
        %%
        %------------------------------------------------------------------
        %In this section, i have defined all the object of data tab. Each 
        % Object is handleobject and represnt one component.  
        
        %htabData: Here all the handle objects will be declared for data
        % tab
        hTxtNeuralBehav% Type:staticText:neural Data and behavioral data
        
        hPbNeuralBehav %Type:pushbutton: to load Neural and Behavioral Data file
        
        hTxtStartOffset %Type:staticText: starting offset
        hTxtEndOffset %Type:staticText: Ending offset
        hEditStartOffset %Type: EditableTextField: asking for staring offset in seconds
        hEditEndOffset  % Type:EditableTextField: asking for ending offset in seconds
        
        hTxtStartOffsetUnit %Type:staticText : unit of time is seconds
        hTxtEndOffsetUnits % Type:staticText : unit of time is second
        
        hPopupStartEvent %Type:popupMenu : starting event
        hTxtStartEvent   %Type:textbox: starting event
        hPopupEndEvent %Type:popupMenu: Ending event
        hTxtEndEvent %Type:Text box : Ending event
        
        %%
        %------------------------------------------------------------------
        %In this section, i have defined all the object of Features Extraction
        % and reduction tab. Each object is handleobject and represnt one
        % component
        % hTabFeatExtRed : all the handle objects will be declared for
        
        hTxtClasses %Type : staticText: for number of possible classes 
        hPopupClasses%Type : popup :All the possible classes 
        hFigClassesSettingsWindow
        
        
        hPnlFeatExtOffline %Type:object of 'uipannel': it will encapsulate 
                            %all the required component(objects)
        hTxtFeatExtOffline% Type : staticText : for features extraction  
        hPopupFeatExtOffline%Type : popup : for features extraction technique
        
        hTxtFeatExtParamTitle %Type:staticText : paramters required for features extraction
        hPopupFeatExtParamSettingsModes%Type:Popup: it will have two options 'Default' and 'customize'
        
        hFigFeatExtParamSettingsWindow %Type:figure: New window will open if, 'customize' setting is choosen  
        %to see the element of this figure please scroll down at the bottom of properties section 
        
        hPbExtractFeatOffline %Type : pushbutton : will extractt features of selected algo
        
        hTxtPlotRawFeatExt % Heading for visulaiztion of raw data and extracted features
        
        hPopupPlotRawFeatExt % Popupmenu : for possible plots that can be done.
                        
        hPbSelectedRawFeatExtAlgo  %Type:pushbutton: This is a pushbutton that willl be used 
                    %to plot raw data
                    
%%         Features Reduction pannel
                     
        hPnlFeatRedOffline %Type:object of 'uipannel': it will encapsulate 
                           %all the required component(objects)            
        hTxtFeatRedOffline  %Type: StaticText : for fetaures reduction
        hPopupFeatRedOffline %Type:Popup: all possible techniques for features 
                                        %redcuctiojn
                                        
        hTxtFeatRedParamTitle %Type:staticText : paramters required for features Reduction
        
        hPopupFeatRedParamSettingsModes%Type:Popup: it will have two options 'Default' and 'customize'
        hFigFeatRedParamSettingsWindow %Type:figure: New window will open if, 'customize' setting is choosen  
        %to see the element of this figure please scroll down at the bottom of properties section 

        
        hPbRedFeatOffline %Type : pushbutton : will extractt features of selected algo
        
        
        hTxtPlotFeatRed % Heading for visulaiztion of raw data and extracted features
        
        hPopupPlotFeatRed % Popupmenu : for possible plots that can be done.
        
        hPbSelectedFeatRedAlgo  %Type:pushbutton: This is a pushbutton that willl be used
                    %to plot raw data
                    
                    
        
        %%
        %In this Secetion i will define all the objcet, required by canvas
        %%'thisFigFeatExtModeCustomize'
        hTxtCustomFeatExtParam
        
        hTxtCustomFeatExtParam1
        hEditCustomFeatExtParam1
        
        %% In this section I willl define all the, required by canvas 
        %'thisFigFeatRedModeCustomize'  
        hTxtCustomFeatRedParam
        
        hTxtCustomFeatRedParam1
        hEditCustomFeatRedParam1
        tTxtCustomFeatRedParam12
        
        hTxtCustomDataDistRatio
        
        hTxtCustomDataDistRatioParam1
        hEditCustomDataDistRatioParam1
        hTxtCustomDataDistRatioParam12
        
        hPbGetCustomFeatRedParamSetting
        
                         
        %%
        %------------------------------------------------------------------
        %In this section, i have defined all the object of decoders tab. Each 
        % Object is handleobject and represnt one component.  
        %hTabDecoder
        hPnlTrainDeco %Type: uipannel : is used to encapsulate all the the
                       % element required to train the decoder
        hTxtTaskType %Type: statictext : is used to label
        hPopupTaskType %Type:Popup: is used to select the decoding module 
        
        hTxtDecoAlgo %Type:staticText: is used to label 
        hPopupDecoAlgo% Type:'popup': is used for all possible 
        
        hTxtParamDecoAlgo%Type:statictext: is used for labeling
                                
        hPopupTrainDecoParamSettingsModes%Type:Popup: it will have two options 'Default' and 'customize'
        hFigTrainDecoParamSettingsWindow %Type:figure: New window will open if, 'customize' setting is choosen  
        %to see the element of this figure please scroll down at the bottom of properties section 
        
        hPbTrain % Type:pushbutton: is used to train the selected machine 
                 % learning algorithm with the selected paramters
        
                 
        hPnlTrainValEval %Type:uipanel: is used to encapsulate all the elements
                         % for ploting
                         
        
        hDecoPerTxt %Type :staticText : is used for labeling
        
        hPopupDecoPer %Type :Popup: is used for differnet evalution metrices
                      % that can be visulaize
       
        hPbDecoPer %Type : Pushbutton: is used to plot selected evalution metric in 
        % in a seperate window
        
        
%         hPbTrainValPer% Type:pushbutton : is used to check training and validation
%                                         % performance of selected algo
% 
%         hPbConfMatTrainVal
% 
%         hPbTop2TrainVal

        
        hPbSaveModel
        
        
        %%In this section, I will define all the required object by 
        %'thisFigClassesSelectionModeCustomize(hSelf)'
        hPnlCustomClassSelection
%         hCBCustomClass1
%         hCBCustomClass2
%         hCBCustomClass3
        hTbCustomClassSelection
        hPbClassesGetData %Type: pushbutton : will be used to get the data of all the selected classes
        %% In this section I willl define all the, required by canvas
        %##################################################################
        %'thisFigTrainDecoModeCustomize'  
        hTxtCustomTrainDecoParam
        
        hTxtCustomTrainDecoParam1
        hEditCustomTrainDecoParam1
        hPbGetCustomDecoAlgoParamSetting
        
        %% new figure: test decoder
        %##################################################################
        %hFigTest %(canvas to evaluate algo)
        %%%%%%%%%%%%%%%%%%%
        hPnlEvalData %Type: uipannel: Will encapsulate all the necessary 
                     % elements for data collection    
        
        hTxtEvalData% Type:textbox: used as title
        
        hTxtEvalDataParam1 % Type:textBox: USed as title
        hPbEvalDataParam1  %Type:pushbutton: Used to get neural and behavioral data: by default it is pb
        hTxtEvalDataParam2  %Type:textBox: Used as title
        hEditEvalDataParam2 %Type: EditBox: By Defaults it is edit box may be later on it is used as different object
        
        hPbEvalRawData %Type: pushbutton : Use to plot raw data 
        
        %%%%%%%%%%%%%%%%%
        hPnlEvalFeatExtRed %Type:uiPannel : Use to encapsulate all the element 
                            % of features extraction mode in evalution(test) mode
                            
        
         hPbEvalFeatExtRed % Type: pushbutton : will extract features and reduce the dimensionality
                            %according previooulsy defined settings                   
         hTxtEvalVisualFeat% Type: textbox : will be used as tiltle for set of 
                            % visulaization pushbutton defined below
         hPopupEValVisualFeat %Type: popup: will be used to plot extracted features
                               % and also features in low dimensions i.e
                               % 2-d,3-d
                               
         hPbEValVisualFeat %Type:pushbuuton: upon pressing this button selection from popupmenu will be plotted
        %%%%%%%%%%
         hPnlEvalTestDeco %Type: uipannel: Will be used to encapuslate all the elmenet related to evaluate 
                            %train model on previusly unseen data
                            
         hPbEvalTestDeco %Type: pushbutton: will be used to test the trained on selecetd unseen data
         
         hTxtEvalTestVisPer %Type:TextBOx:will be used as title
         
         hPopupEvalTestVisPer %Type:  will be used to select and plot the evalution metric
         
         hPbEvalTesVisPer %Type: pushbutton :Upon preesing this button, selected metric on popupmenu will be ploted on 
         %seperate window

                               
   end
    methods
        function hSelf = GUIBCIFW2(controller)
            hSelf.controller=controller;
            %%
            figWidth=0.50;
            figHeight=0.50;
            hSelf.hFig=figure(...
                'NumberTitle','off', ...
                'MenuBar','none', ...
                'ToolBar','none',...
                'Name','BCI Framework',...
                'Units','normalized', ...
                'Position',[0.25,0.35,figWidth,figHeight]);
            %Defining tab group
            hSelf.hTabGpBCI = uitabgroup(hSelf.hFig,'Position',[.01 .01 .9 .9]);
            %open the configuration file
            fid = fopen('configBCIFW2.m','r'); %open configuration file
            cmdStringMatrix = fscanf(fid,'%c'); %read whole text from Matlab
            fclose(fid);
            %eval(cmdStringMatrix) %interpret text as Matlab commands
            thisData(hSelf,cmdStringMatrix) %Intializing all the objects of 'Data' tab
            thisFeaturesExtractionReduction(hSelf,cmdStringMatrix) %Initilazing all the objects of 'FeaturesExtraction&Reduction'tab 
            thisDecoder(hSelf,cmdStringMatrix) %Intializing all the objects of 'Decoders' tab
            thisDecoderTestOffline(hSelf,cmdStringMatrix) %Intializing aal the objects of 'hTabDecoderTestOfflineTab';
            
        end
        function thisData(hSelf,cmdStringMatrix)
            %%
            hSelf.hTabData = uitab('Parent', hSelf.hTabGpBCI,...
                'Title','Data',...
                'BackgroundColor','white');
           
            hSelf.hTxtNeuralBehav=uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Neural&BehavioralData:', ...
                'FontSize',10,...
                'HorizontalAlignment','center', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.25,0.80,0.22,0.07]);
            
            hSelf.hPbNeuralBehav = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','pushbutton',...
                'String','Browse', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.50,0.80,0.10,0.07]);
            set(hSelf.hPbNeuralBehav, 'callback', @(src, event) hPbNeuralBehavCallback(hSelf, src, event));
            
            
            hSelf.hTxtStartOffset = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','StartingOffset:', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.05,0.55,0.12,0.07]);
            
            hSelf.hEditStartOffset = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','edit',...
                'String','0.0', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.19,0.55,0.10,0.07]);
             
            eval(cmdStringMatrix)
            if exist('startingOffset','var') && ischar(startingOffset)
                set(hSelf.hEditStartOffset,'String',startingOffset);
            end
            
            set(hSelf.hEditStartOffset, 'callback', @(src, event) hEditStartOffsetCallback(hSelf, src, event));
            
            hSelf.hTxtStartOffsetUnit = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Seconds', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.29,0.55,0.10,0.07]);
            
            hSelf.hTxtEndOffset = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','EndingOffset:', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.50,0.55,0.12,0.07]);
            
            
            hSelf.hEditEndOffset=uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','edit',...
                'String','0.0', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.64,0.55,0.12,0.07]);
             set(hSelf.hEditEndOffset, 'callback', @(src, event) hEditEndOffsetCallback(hSelf, src, event));
                      
              if exist('endingOffset','var') && ischar(endingOffset)
                 set(hSelf.hEditEndOffset,'String',endingOffset);
              end
            
            hSelf.hTxtEndOffsetUnits = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Seconds', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.76,0.55,0.10,0.07]);
            
            
            
            hSelf.hTxtStartEvent = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Starting from Event', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.22,0.30,0.20,0.07]);
            
            
            hSelf.hPopupStartEvent = uicontrol (...
                'Parent',hSelf.hTabData, ... 
                'Style', 'popup', ...
                'FontSize',10,...
                'String',{'------'},...
                'Units', 'normalized', ...
                'Position', [0.43,0.27,0.1,0.1]);
            
            set(hSelf.hPopupStartEvent, 'callback', @(src, event) hPopupStartEventCallback(hSelf, src, event));
            
            hSelf.hTxtEndEvent = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','to', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.54,0.30,0.07,0.07]);
            
            hSelf.hPopupEndEvent = uicontrol (...
                'Parent',hSelf.hTabData, ...
                'Style', 'popup', ...
                'FontSize',10,...
                'String',{'-------'},...
                'Units', 'normalized', ...
                'Position', [0.62,0.27,0.1,0.1]);
            set(hSelf.hPopupEndEvent,'callback', @(src,event)hPopupEndEventCallback(hSelf, src, event))
            
        end
              
        
        
        function thisFeaturesExtractionReduction(hSelf,cmdStringMatrix)
            %%
            %Defining the object for tab FeaturesExtraction&Reduction: 
            hSelf.hTabFeatExtRed = uitab(...
                'Parent',hSelf.hTabGpBCI,...
                'Title','FeaturesExtraction&Redcution',...
                'BackgroundColor','white');
%--------------------------------------------------------------------------            
            %Now start populating the tab by different required objects:
            hSelf.hTxtClasses = uicontrol(...
                'Parent', hSelf.hTabFeatExtRed, ...
                'Style','text',...
                'String','Classes', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.325,0.90,0.15,0.07]);
            
            
            hSelf.hPopupClasses = uicontrol (...
                'Parent',hSelf.hTabFeatExtRed, ... 
                'Style', 'popup', ...
                'String',{'---'},...
                'Units', 'normalized', ...
                'Position', [0.325,0.83,0.15,0.1]);
            eval(cmdStringMatrix)
            if exist('classes','var') && iscell(classes)
                set(hSelf.hPopupClasses,...
                    'String',classes)
            end
            
            set(hSelf.hPopupClasses,'callback', @(src,event)hPopupClassesCallback(hSelf, src, event))
            

            
 %-------------------------------------------------------------------------           
            hSelf.hPnlFeatExtOffline =uipanel(...
                'Parent',hSelf.hTabFeatExtRed, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','FeaturesExtraction',...
                'Position',[0.05,0.52,0.90,0.33]);
            
            hSelf.hTxtFeatExtOffline = uicontrol(...
                'Parent', hSelf.hPnlFeatExtOffline, ...
                'Style','text',...
                'String','FeaturesExtraction', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.03,0.65,0.18,0.20]);
            
            hSelf.hPopupFeatExtOffline = uicontrol (...
                'Parent',hSelf.hPnlFeatExtOffline, ... 
                'Style', 'popup', ...
                'String',{'---'},...
                'Units', 'normalized', ...
                'FontSize',10,...
                'Position', [0.03,0.452,0.18,0.20]);
            
            if exist('featuresExtraction','var') && iscell(featuresExtraction)
                set(hSelf.hPopupFeatExtOffline,...
                    'String',featuresExtraction)
            end
            set(hSelf.hPopupFeatExtOffline, 'callback', @(src, event) hPopupFeatExtOfflineCallback(hSelf, src, event));
            
            
            hSelf.hTxtFeatExtParamTitle = uicontrol(...
                'Parent', hSelf.hPnlFeatExtOffline, ...
                'Style','text',...
                'String','Parameters', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.24,0.65,0.18,0.20]);
            
             
            hSelf.hPopupFeatExtParamSettingsModes= uicontrol(...
                'Parent',  hSelf.hPnlFeatExtOffline, ...
                'Style','popup',...
                'String',{'----------------'}, ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.24,0.452,0.18,0.20]);
             
            set(hSelf.hPopupFeatExtParamSettingsModes, 'callback', @(src, event) hPopupFeatExtParamSettingsModesCallback(hSelf, src, event));
            
            
            hSelf.hPbExtractFeatOffline= uicontrol(...
                'Parent', hSelf.hPnlFeatExtOffline, ...
                'Style','pushbutton',...
                'String','Extract', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.45,0.55,0.15,0.20]);
             
            set(hSelf.hPbExtractFeatOffline, 'callback', @(src, event) hPbExtractFeatOfflineCallback(hSelf, src, event));

            hSelf.hTxtPlotRawFeatExt = uicontrol(...
                'Parent', hSelf.hPnlFeatExtOffline, ...
                'Style','text',...
                'String','VisualizeData', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.63,0.65,0.18,0.20]);
            
             hSelf.hPopupPlotRawFeatExt = uicontrol(...
                'Parent', hSelf.hPnlFeatExtOffline, ...
                'Style','popup',...
                'String','------------------------', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.63,0.45,0.18,0.20]);
            
            
            hSelf.hPbSelectedRawFeatExtAlgo = uicontrol (...
                'Parent',hSelf.hPnlFeatExtOffline,...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','Visualize',...
                'Units','normalize',...
                'Position',[0.84,0.55,0.15,0.20]);
            
%--------------------------------------------------------------------------
            hSelf.hPnlFeatRedOffline = uipanel(...
                'Parent',hSelf.hTabFeatExtRed, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','FeaturesReduction',...
                'Position',[0.05,0.15,0.90,0.33]);
            
            hSelf.hTxtFeatRedOffline = uicontrol(...
                'Parent', hSelf.hPnlFeatRedOffline, ...
                'Style','text',...
                'FontSize',10,...
                'String','FeaturesReduction', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.03,0.65,0.18,0.20]);
            
            hSelf.hPopupFeatRedOffline =  uicontrol (...
                'Parent',hSelf.hPnlFeatRedOffline, ... 
                'Style', 'popup', ...
                'String',{'---'},...
                'Units', 'normalized', ...
                'Position', [0.03,0.452,0.18,0.20]);
            
            if exist('featuresReduction','var') && iscell(featuresReduction)
                set(hSelf.hPopupFeatRedOffline,...
                    'String',featuresReduction)
            end
            
             set(hSelf.hPopupFeatRedOffline, 'callback', @(src, event) hPopupFeatRedOfflineCallback(hSelf, src, event));
            
            
            hSelf.hTxtFeatRedParamTitle =  uicontrol(...
                'Parent', hSelf.hPnlFeatRedOffline, ...
                'Style','text',...
                'String','Parameters', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.24,0.65,0.18,0.20]);
            
             
          hSelf.hPopupFeatRedParamSettingsModes = uicontrol(...
                'Parent',  hSelf.hPnlFeatRedOffline, ...
                'Style','popup',...
                'String',{'----------------'}, ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.24,0.452,0.18,0.20]);
            
             
            set(hSelf.hPopupFeatRedParamSettingsModes, 'callback', @(src, event) hPopupFeatRedParamSettingsModesCallback(hSelf, src, event));
            
            hSelf.hPbRedFeatOffline= uicontrol(...
                'Parent', hSelf.hPnlFeatRedOffline, ...
                'Style','pushbutton',...
                'String','Reduction', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.45,0.55,0.15,0.20]);
            set(hSelf.hPbRedFeatOffline, 'callback', @(src, event) hPbRedFeatOfflineCallback(hSelf, src, event));
            
            hSelf.hTxtPlotFeatRed = uicontrol(...
                'Parent', hSelf.hPnlFeatRedOffline, ...
                'Style','text',...
                'String','VisualizeFeatures', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.63,0.65,0.18,0.20]);
            
            hSelf.hPopupPlotFeatRed = uicontrol(...
                'Parent', hSelf.hPnlFeatRedOffline, ...
                'Style','popup',...
                'String','------------------------', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.63,0.45,0.18,0.20]);
            
            
            hSelf.hPbSelectedFeatRedAlgo = uicontrol (...
                'Parent',hSelf.hPnlFeatRedOffline,...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','Visualize',...
                'Units','normalize',...
                'Position',[0.84,0.55,0.15,0.20]);
            
            set(hSelf.hPbSelectedFeatRedAlgo, 'callback', @(src, event) hPbSelectedFeatRedAlgoCallback(hSelf, src, event))
            
                     
  %------------------------------------------------------------------------          

                  
            
        end
        
        function thisDecoder(hSelf,cmdStringMatrix)
            %%
            hSelf.hTabDecoder = uitab(...
                'Parent',hSelf.hTabGpBCI,...
                'Title','Decoder',...
                'BackgroundColor','white');
            
            hSelf.hPnlTrainDeco = uipanel(...
                'Parent',hSelf.hTabDecoder, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','TrainDecoder',...
                'Position',[0.05,0.60,0.90,0.33]);
            
            hSelf.hTxtTaskType = uicontrol(...
                'Parent', hSelf.hPnlTrainDeco, ...
                'Style','text',...
                'FontSize',10,...
                'String','TrialType', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.01,0.70,0.15,0.15]);
            
            hSelf.hPopupTaskType = uicontrol (...
                'Parent',hSelf.hPnlTrainDeco, ... 
                'Style', 'popup', ...
                'String',{'Classification',...
                'Regression'},...
                'Units', 'normalized', ...
                'Position', [0.01,0.55,0.15,0.15]);
            
            set(hSelf.hPopupTaskType, 'callback', @(src, event) hPopupTaskTypeCallback(hSelf, src, event));
            
            hSelf.hTxtDecoAlgo=uicontrol(...
                'Parent', hSelf.hPnlTrainDeco, ...
                'Style','text',...
                'FontSize',10,...
                'String','Decoding Algorithms', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.20,0.70,0.20,0.15]);
            
            hSelf.hPopupDecoAlgo = uicontrol (...
                'Parent',hSelf.hPnlTrainDeco, ... 
                'Style', 'popup', ...
                'String',{'--------------------------'},...
                'Units', 'normalized', ...
                'Position', [0.20,0.595,0.20,0.1]);     
            
            set(hSelf.hPopupDecoAlgo, 'callback', @(src, event) hPopupDecoAlgoCallback(hSelf, src, event));
            
            
            hSelf.hTxtParamDecoAlgo =uicontrol(...
                'Parent', hSelf.hPnlTrainDeco, ...
                'Style','text',...
                'FontSize',10,...
                'String','Parameters', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.70,0.30,0.20]);
            
          %hPopupTrainDecoParamSettingsModes%Type:Popup: it will have two options 'Default' and 'customize'
%         hFigTrainDecoParamSettingsWindow
 
            hSelf.hPopupTrainDecoParamSettingsModes = uicontrol(...
                'Parent',  hSelf.hPnlTrainDeco, ...
                'Style','popup',...
                'String',{'----------------'}, ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.45,0.5,0.30,0.20]);
            
             
            set(hSelf.hPopupTrainDecoParamSettingsModes, 'callback', @(src, event) hPopupTrainDecoParamSettingsModesCallback(hSelf, src, event));
                     
            
            
            hSelf.hPbTrain =   uicontrol(...
                'Parent',hSelf.hPnlTrainDeco,...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','Train',...
                'Units','normalize',...
                'Position',[0.80,0.50,0.19,0.35]);
            set(hSelf.hPbTrain, 'callback', @(src, event) hPbTrainCallback(hSelf, src, event));
            
            hSelf.hPnlTrainValEval = uipanel(...
                'Parent',hSelf.hTabDecoder, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','Evaluate Training & Validation Performance',...
                'Position',[0.25,0.05,0.50,0.50]);
            
            hSelf.hDecoPerTxt = uicontrol(...
                'Parent',hSelf.hPnlTrainValEval,...
                'Style', 'text', ...
                'String', 'Performance', ...
                'FontSize',10,...
                'Units', 'normalized', ...
                'Position', [0.10,0.75,0.35,0.15]);
            
            hSelf.hPopupDecoPer =  uicontrol(...
                'Parent',hSelf.hPnlTrainValEval,...
                'Style', 'popup', ...
                'String', '......', ...
                'FontSize',10,...
                'Units', 'normalized', ...
                'Position', [0.10,0.60,0.35,0.15]);
            
            hSelf.hPbDecoPer = uicontrol(...
                'Parent',hSelf.hPnlTrainValEval,...
                'Style', 'pushbutton', ...
                'String', 'Plot', ...
                'FontSize',10,...
                'Units', 'normalized', ...
                'Position', [0.50,0.65,0.35,0.25]);
             set(hSelf.hPbDecoPer, 'callback', @(src, event) hPbDecoPerCallback(hSelf, src, event));

            
            hSelf.hPbSaveModel = uicontrol(...
                'Parent',hSelf.hPnlTrainValEval,...
                'Style','pushbutton',...
                'String','SaveModel',...
                'Units','normalize',...
                'Position',[0.35,0.15,0.35,0.30]);
            

            
            
        end
        function thisDecoderTestOffline(hSelf,cmdStringMatrix)
            
            
            hSelf.hTabDecoderTestOffline =uitab(...
                'Parent',hSelf.hTabGpBCI,...
                'Title','TestDecoder-Offline',...
                'BackgroundColor','white');
            
            hSelf.hPnlEvalData = uipanel(...
                'Parent',hSelf.hTabDecoderTestOffline, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','Data',...
                'Units','normalize',...
                'Position',[0.25,0.65,0.50,0.30]);
                      
            
            hSelf.hTxtEvalData = uicontrol(...
                'Parent', hSelf.hPnlEvalData, ...
                'Style','text',...
                'FontSize',10,...
                'String','Data', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.60,0.50,0.25]);
            
            hSelf.hTxtEvalDataParam1= uicontrol(...
                'Parent', hSelf.hPnlEvalData, ...
                'Visible','on', ...
                'Style','text',...
                'String','Neural&BehavData', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.36,0.25,0.25]);
            
            hSelf.hPbEvalDataParam1 = uicontrol(...
                'Parent', hSelf.hPnlEvalData, ...
                'Visible','on', ...
                'Style','pushbutton',...
                'String','Browse', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.35,0.36,0.25,0.25]);
            
            set(hSelf.hPbEvalDataParam1, 'callback', @(src, event) hPbEvalDataParam1Callback(hSelf, src, event));
            
            hSelf.hTxtEvalDataParam2 = uicontrol(...
                'Parent', hSelf.hPnlEvalData, ...
                'Style','text',...
                'Visible','on', ...
                'String','TrialIndices', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.12,0.25,0.25]);
                 
             hSelf.hEditEvalDataParam2 =uicontrol(...
                'Parent', hSelf.hPnlEvalData, ...
                'Visible','on', ...
                'Style','edit',...
                'String','[session]', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.35,0.12,0.25,0.25]);
            
             
            
            hSelf.hPbEvalRawData = uicontrol(...
                'Parent', hSelf.hPnlEvalData, ...
                'Visible','on', ...
                'Enable','on', ...
                'Style','pushbutton',...
                'String','PlotRawData', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.65,0.25,0.25,0.40]);
            
            %--------------------------------------------------------------
            hSelf.hPnlEvalFeatExtRed = uipanel(...
                'Parent',hSelf.hTabDecoderTestOffline, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','FeaturesExtraction&Reduction',...
                'Units','normalize',...
                'Position',[0.05,0.05,0.425,0.55]);

             
            
            hSelf.hPbEvalFeatExtRed = uicontrol(...
                'Parent', hSelf.hPnlEvalFeatExtRed, ...
                'Visible','on', ...
                'Enable','on', ...
                'Style','pushbutton',...
                'String','ExtractFeatures', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.25,0.55,0.50,0.30]);
            
            
            hSelf.hTxtEvalVisualFeat = uicontrol(...
                'Parent', hSelf.hPnlEvalFeatExtRed, ...
                'Style','text',...
                'FontSize',10,...
                'String','VisualizeData', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.05,0.30,0.40,0.15]);
            
            hSelf.hPopupEValVisualFeat = uicontrol (...
                'Parent', hSelf.hPnlEvalFeatExtRed, ...
                'Style','popup',...
                'FontSize',10,...
                'String','---------', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.05,0.15,0.40,0.15]);
            
            hSelf.hPbEValVisualFeat = uicontrol (...
                'Parent', hSelf.hPnlEvalFeatExtRed, ...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','Plot', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.55,0.25,0.40,0.15]);

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

            hSelf.hPnlEvalTestDeco = uipanel(...
                'Parent',hSelf.hTabDecoderTestOffline, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Fontweight','bold', ...
                'Title','Test Decoder',...
                'Units','normalize',...
                'Position',[0.525,0.05,0.425,0.55]);
            
            
            hSelf.hPbEvalTestDeco = uicontrol(...
                'Parent', hSelf.hPnlEvalTestDeco, ...
                'Visible','on', ...
                'Enable','on', ...
                'Style','pushbutton',...
                'String','TestModel', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.25,0.55,0.50,0.30]);
            
            hSelf.hTxtEvalTestVisPer = uicontrol(...
                'Parent', hSelf.hPnlEvalTestDeco, ...
                'Style','text',...
                'FontSize',10,...
                'String','EvaluatePerformace', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.05,0.30,0.40,0.15]);

            
            hSelf.hPopupEvalTestVisPer = uicontrol (...
                'Parent', hSelf.hPnlEvalTestDeco, ...
                'Style','popup',...
                'FontSize',10,...
                'String','---------', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.05,0.15,0.40,0.15]);
            
            hSelf.hPbEvalTesVisPer = uicontrol (...
                'Parent', hSelf.hPnlEvalTestDeco, ...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','Plot', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.55,0.25,0.40,0.15]);
            
            

            
        end
        function thisFigClassesSelectionModeCustomize(hSelf)
            %%
            %hPnlCustomClassSelection
        %hCBCustomClass1
        %hCBCustomClass2
        %hCBCustomClass3
        hSelf.hPnlCustomClassSelection = uipanel(...
            'Parent',hSelf.hFigClassesSettingsWindow, ...
            'BackgroundColor','white', ...
            'FontSize',10,...
            'Fontweight','bold', ...
            'Title','Classes',...
            'Units','normalize',...
            'Position',[0.01,0.10,0.70,0.80]);
%         hSelf.hCBCustomClass1 = uicontrol (...
%             'Parent', hSelf.hPnlCustomClassSelection, ...
%             'Style','checkbox',...
%             'FontSize',10,...
%             'String','Rock', ...
%             'units','normalized', ...
%             'HorizontalAlignment','center', ...
%             'Position', [0.15,0.75,0.70,0.15]);
%         
%         hSelf.hCBCustomClass2 = uicontrol (...
%             'Parent', hSelf.hPnlCustomClassSelection, ...
%             'Style','checkbox',...
%             'FontSize',10,...
%             'String','Paper', ...
%             'units','normalized', ...
%             'HorizontalAlignment','center', ...
%             'Position', [0.15,0.55,0.70,0.15]);
%         
%         hSelf.hCBCustomClass3 = uicontrol (...
%             'Parent', hSelf.hPnlCustomClassSelection, ...
%             'Style','checkbox',...
%             'FontSize',10,...
%             'String','Scissors', ...
%             'units','normalized', ...
%             'HorizontalAlignment','center', ...
%             'Position', [0.15,0.35,0.70,0.15]);

        hSelf.hTbCustomClassSelection=uitable(...
            'Parent', hSelf.hPnlCustomClassSelection, ...
            'Units','normalized', ...
            'Data',{'Rock',false;'Paper',false;'Scissors',false},...
            'ColumnName',{'TrialTypes','Status'}, ...
            'Position',[0.1,0.1,0.70,0.70],...
            'ColumnEditable',true);
        
        hSelf.hPbClassesGetData = uicontrol (...
            'Parent',hSelf.hFigClassesSettingsWindow, ...
            'Style', 'pushbutton', ...
            'String','Apply',...
            'Units', 'normalized', ...
            'Position', [0.72,0.50,0.25,0.20]);
       set(hSelf.hPbClassesGetData, 'callback', @(src, event) hPbClassesGetDataCallback(hSelf, src, event)); 
            
        end
        function thisFigFeatExtModeCustomize(hSelf)
            %%
            hSelf.hTxtCustomFeatExtParam = uicontrol(...
                'Parent',hSelf.hFigFeatExtParamSettingsWindow,...
                'Style','text',...
                'String','Paramters',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.01,0.80,0.98,0.20]);
            hSelf.hTxtCustomFeatExtParam1 = uicontrol(...
                'Parent',hSelf.hFigFeatExtParamSettingsWindow,...
                'Style','text',...
                'String','Paramters',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.01,0.60,0.49,0.20]);
             
            hSelf.hEditCustomFeatExtParam1 = uicontrol(...
                'Parent',hSelf.hFigFeatExtParamSettingsWindow,...
                'Style','edit',...
                'String','',...
                'Units','normalize',...
                'Position',[0.49,0.60,0.49,0.20]);
            
            
        end
        function thisFigFeatRedModeCustomize(hSelf)
            %%
             hSelf.hTxtCustomFeatRedParam = uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','text',...
                'String','Paramters',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.01,0.85,0.98,0.15]);
            hSelf.hTxtCustomFeatRedParam1 = uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','text',...
                'String','Paramters',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.01,0.70,0.49,0.15]);
             
            hSelf.hEditCustomFeatRedParam1 = uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','edit',...
                'String','',...
                'Units','normalize',...
                'Position',[0.49,0.70,0.20,0.15]);
            
            hSelf.tTxtCustomFeatRedParam12= uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','text',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.69,0.65,0.10,0.15]);
             
             hSelf.hTxtCustomDataDistRatio = uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','text',...
                'String','Data Distribution Ratio',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.01,0.50,0.98,0.15]);
            
            hSelf.hTxtCustomDataDistRatioParam1 = uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','text',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.01,0.30,0.49,0.15]);
            
            hSelf.hEditCustomDataDistRatioParam1 = uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','edit',...
                'String','',...
                'Units','normalize',...
                'Position',[0.49,0.30,0.20,0.15]);
            
            hSelf.hTxtCustomDataDistRatioParam12=uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','text',...
                'FontSize',10, ...
                'Units','normalize',...
                'Position',[0.69,0.25,0.10,0.15]);
            
            hSelf.hPbGetCustomFeatRedParamSetting =uicontrol(...
                'Parent',hSelf.hFigFeatRedParamSettingsWindow,...
                'Style','pushbutton',...
                'FontSize', 10, ...
                'Units','normalize',...
                'String','Apply', ...
                'Position',[0.35,0.10,0.30,0.15]);
            
            set(hSelf.hPbGetCustomFeatRedParamSetting, 'callback', @(src, event) hPbGetCustomFeatRedParamSettingCallback(hSelf, src, event));



            
        end
        function thisFigTrainDecoModeCustomize(hSelf)
            %%

            hSelf.hTxtCustomTrainDecoParam =  uicontrol(...
                'Parent',hSelf.hFigTrainDecoParamSettingsWindow,...
                'Style','text',...
                'String','Paramters',...
                'FontSize',12, ...
                'FontWeight','bold', ...
                'Units','normalize',...
                'Position',[0.01,0.70,0.98,0.20]);
            hSelf.hTxtCustomTrainDecoParam1 = uicontrol(...
                'Parent',hSelf.hFigTrainDecoParamSettingsWindow,...
                'Style','text',...
                'String','Paramters',...
                'FontSize',12, ...
                'Units','normalize',...
                'Position',[0.01,0.52,0.49,0.20]);
            hSelf.hEditCustomTrainDecoParam1 = uicontrol(...
                'Parent',hSelf.hFigTrainDecoParamSettingsWindow,...
                'Style','edit',...
                'String','',...
                'Units','normalize',...
                'Position',[0.38,0.55,0.49,0.20]);
            
            hSelf.hPbGetCustomDecoAlgoParamSetting = uicontrol(...
                'Parent',hSelf.hFigTrainDecoParamSettingsWindow,...
                'Style','pushbutton',...
                'FontSize', 12, ...
                'Units','normalize',...
                'String','Apply', ...
                'Position',[0.35,0.30,0.30,0.15]);
            set(hSelf.hPbGetCustomDecoAlgoParamSetting, 'callback', @(src, event) hPbGetCustomDecoAlgoParamSettingCallback(hSelf, src, event));
            
        end
        
         
        
%         %----------------------------------------------------------------
%         %----------------Callbacks(Data Tab)-----------------------------
%         %----------------------------------------------------------------

            function hPbNeuralBehavCallback(hSelf, src, event)
                hSelf.controller.setNeuralSpikesBehavioralData()
            end
            
            function hEditStartOffsetCallback(hSelf, src, event)
                startingOffset=str2num(get(hSelf.hEditStartOffset,'String'));
                hSelf.controller.setStartingOffset(startingOffset)
            
            end
            
            function hEditEndOffsetCallback(hSelf, src, event)
                endingOffset = str2num(get(hSelf.hEditEndOffset,'String'));
                hSelf.controller.setEndingOffset(endingOffset);
            end
            
            
            function  hPopupStartEventCallback(hSelf, src, event)
                %startingEvents = get(hSelf.hPopupStartEvent,'String');
                selectedEventInd=get(hSelf.hPopupStartEvent,'Value');
                hSelf.controller.setStartingEvent(selectedEventInd);              
                
            end
            
            function hPopupEndEventCallback(hSelf,src,event)
                selectedEventInd=get(hSelf.hPopupEndEvent,'Value');
                hSelf.controller.setEndingEvent(selectedEventInd);  
            end
            
            
            
         %-----------------------------------------------------------------
         %------------------ Callbacks(FeaturesExtraction&ReductionTab) ---
         %-----------------------------------------------------------------
         
         function hPopupClassesCallback(hSelf,src,event)
             selectionModes= get(hSelf.hPopupClasses,'String');
             selectedMode = get(hSelf.hPopupClasses,'Value');
             selctedModeName =selectionModes{selectedMode};
             switch selctedModeName
                 case 'All'
                 case 'Customize'
                     figWidth=0.2;
                     figHeight=0.2;
                     hSelf.hFigClassesSettingsWindow = figure(...
                         'NumberTitle','off', ...
                         'MenuBar','none', ...
                         'ToolBar','none',...
                         'Name','SelectClasses',...
                         'Units','normalized', ...
                         'Position',[0.50,0.50,figWidth,figHeight]);
                     thisFigClassesSelectionModeCustomize(hSelf)
                     
             end
             
         end
         function hPopupFeatExtOfflineCallback(hSelf, src, event)
             featExtAlgos= get(hSelf.hPopupFeatExtOffline,'String');
             selectedAlgoInd=get(hSelf.hPopupFeatExtOffline,'Value');
             selectedAlgoName =featExtAlgos{selectedAlgoInd};
             hSelf.controller.getFeaturesExtAlgo(selectedAlgoName);
         end
         
         function  hPopupFeatExtParamSettingsModesCallback(hSelf, src, event)
             availSettings=get(hSelf.hPopupFeatExtParamSettingsModes,'String');
             selectedSettingInd = get(hSelf.hPopupFeatExtParamSettingsModes,'Value');
             selectedSettingName = availSettings{selectedSettingInd};
             switch selectedSettingName
                 case 'Customize'
                     figWidth=0.1;
                     figHeight=0.2;
                     hSelf.hFigFeatExtParamSettingsWindow =figure(...
                         'NumberTitle','off', ...
                         'MenuBar','none', ...
                         'ToolBar','none',...
                         'Name','FeatureExtractionAlgoParameters',...
                         'Units','normalized', ...
                         'Position',[0.50,0.50,figWidth,figHeight]);
                     thisFigFeatExtModeCustomize(hSelf)
             end
             hSelf.controller.getFeatExtParamSettingMod(selectedSettingName);
         end
         function hPbExtractFeatOfflineCallback(hSelf, src, event)
             hSelf.controller.getExtractFeatOffline();
         end
         
         
         function hPopupFeatRedOfflineCallback(hSelf, src, event)
             featRedAlgos= get(hSelf.hPopupFeatRedOffline,'String');
             selectedAlgoInd=get(hSelf.hPopupFeatRedOffline,'Value');
             selectedAlgoName =featRedAlgos{selectedAlgoInd};
             hSelf.controller.getFeaturesRedAlgo(selectedAlgoName);

             
         end
         
         function hPopupFeatRedParamSettingsModesCallback(hSelf, src, event)
             availSettings=get(hSelf.hPopupFeatRedParamSettingsModes,'String');
             selectedSettingInd = get(hSelf.hPopupFeatRedParamSettingsModes,'Value');
             selectedSettingName = availSettings{selectedSettingInd};
             switch selectedSettingName
                 case 'Customize'
                     figWidth=0.15;
                     figHeight=0.2;
                     hSelf.hFigFeatRedParamSettingsWindow =figure(...
                         'NumberTitle','off', ...
                         'MenuBar','none', ...
                         'ToolBar','none',...
                         'Name','FeatureReductionAlgoParameters',...
                         'Units','normalized', ...
                         'Position',[0.50,0.50,figWidth,figHeight]);
                     thisFigFeatRedModeCustomize(hSelf)
                     
             end
              hSelf.controller.getFeatRedParamSettingMod(selectedSettingName);
             
         end
         
         function hPbRedFeatOfflineCallback(hSelf, src, event)
             hSelf.controller.getReduceFeatOffline();
         end
         function hPbSelectedFeatRedAlgoCallback(hSelf, src, event)
             hSelf.controller.plotReducedFeaturesPCA();
         end
         
         %--Clasess(Customize)---------------------------------------------
        
         function hPbClassesGetDataCallback(hSelf, src, event)
             data=get(hSelf.hTbCustomClassSelection, 'Data');
             values=cell2mat(data(:,2));
             indicesSelectedClass=(find(values==1))';
             if isempty(indicesSelectedClass)
                 msgbox('your selection is not valid')
             else 
                indicesSelectedClass=num2str(indicesSelectedClass);
                set(hSelf.hPbClassesGetData, ...
                 'Tag',indicesSelectedClass)
             end
             
         end
         
         %--FeatRed(ParamtersSetting & Visualizing)------------------------
         
         function hPbGetCustomFeatRedParamSettingCallback(hSelf, src, event)
             ParamSettings=get(hSelf.hEditCustomFeatRedParam1,'String');
             DataDistribuitionRatio = get(hSelf.hEditCustomDataDistRatioParam1,'String');
             ParamSettings=str2num(ParamSettings);
             DataDistribuitionRatio=str2num(DataDistribuitionRatio);
             featRedSettings=struct('ParamSetting',ParamSettings,...
                 'DataDistribuitionRatio',DataDistribuitionRatio);
             featRedSettings=struct2str(featRedSettings)
             set(hSelf.hPbGetCustomFeatRedParamSetting, ...
                 'Tag',featRedSettings)       
             
         end
         
%         
%         %----------------------------------------------------------------
%         %----------------Callbacks(Decoders Tab)-------------------------
%         %----------------------------------------------------------------
%         
%        

        function hPopupTaskTypeCallback(hSelf, src, event)
             decoMods= get(hSelf.hPopupTaskType,'String');
             selectedAlgoInd=get(hSelf.hPopupTaskType,'Value');
             selectedAlgoName =decoMods{selectedAlgoInd};
             hSelf.controller.getDecoMod(selectedAlgoName);
            
        end
        
        %--DecodingAlgo(Custom:PrametersSetting)---------------------------
        
        function  hPbGetCustomDecoAlgoParamSettingCallback(hSelf, src, event)
            decoParameterSetting=get(hSelf.hEditCustomTrainDecoParam1,'String');
            set(hSelf.hPbGetCustomDecoAlgoParamSetting, ...
                 'Tag',decoParameterSetting);
        end
        



        function hPopupDecoAlgoCallback(hSelf, src, event)
            %calling the static function of  class
            %CallbacksGUIBCIFW2.hPopupDecoAlgoCallback(hSelf)
            decoAlgos= get(hSelf.hPopupDecoAlgo,'String');
            selectedAlgoInd=get(hSelf.hPopupDecoAlgo,'Value');
            selectedAlgoName =decoAlgos{selectedAlgoInd};
            hSelf.controller.getDecoAlgo(selectedAlgoName);
            
        end
        
        function hPopupTrainDecoParamSettingsModesCallback(hSelf, src, event)
            availSettings= get(hSelf.hPopupTrainDecoParamSettingsModes,'String');
            selectedSettingInd=get(hSelf.hPopupTrainDecoParamSettingsModes,'Value');
            selectedSettingName =availSettings{selectedSettingInd};
            switch selectedSettingName
                 case 'Customize'
                     figWidth=0.15;
                     figHeight=0.2;
                     hSelf.hFigTrainDecoParamSettingsWindow =figure(...
                         'NumberTitle','off', ...
                         'MenuBar','none', ...
                         'ToolBar','none',...
                         'Name','DecodingAlgoParams',...
                         'Units','normalized', ...
                         'Position',[0.50,0.50,figWidth,figHeight]);
                     thisFigTrainDecoModeCustomize(hSelf)
                     
            end
             hSelf.controller.getTrainDecoParamSettingMod(selectedSettingName);
            
        end
        
        function  hPbTrainCallback(hSelf, src, event)
            hSelf.controller.trainSelectedDecoAlgo();
        end
        function hPbDecoPerCallback(hSelf, src, event)
            hSelf.controller.plotDecoderSelectedPerformanceMeasure();
        end
        
         %------------------------------------------------------------
         %--------------- Callbacks(TestDecoder-Offline) -------------
         %------------------------------------------------------------
         
         function hPbEvalDataParam1Callback(hSelf, src, event)
             hSelf.controller.setNeuralBehavDataTest()
             
         end


                    

    end
end