classdef GUIBCIFW < handle
    properties
        %%
        hFig %Parent(Canvas)
        %%
        hDataPnl %static txt:DataPnnel
        
        hTxtNeural% static text:neural Data
        hTxtBeh %static text : behavioral Data
        hPbNeural %pushbutton : Neural Data
        hPbBeh %pushbutton : behavioral Data
        
        hTxtNeuralName % static text: neural data name(file name)
        hTxtBehName % stataic text: behavioral data name(file name)
        
        hTxtStartOffset %static text : starting offset
        hTxtEndOffset %static text : Ending offset
        
        hEditStartOffset % Editable text field: asking for staring offset in seconds
        hEditEndOffset  % Editable text field: asking for ending offset in seconds
        
        hTxtStartOffsetUnit %static text : unit of time is seconds
        hTxtEndOffsetUnits % static text : unit of time is second
        
        hPopupStartEvent %popup menu : starting event
        hTxtStartEvent   %text box: starting event
        hPopupEndEvent %popup menu: Ending event
        hTxtEndEvent %text box : Ending event
        %%
        hFeatExtPnl
        
        hTxtClasses
        
        hPopupClasses
        
        hTxtFeatExtOffline
        hPopupFeatExtOffline
        
        hTxtFeatRedOffline
        hPopupFeatRedOffline
        
        hPlotFeatRedPnl
        hPbFeatRedPlot2D
        hPbFeatRedPlot3D
        %%
        hDecoPnl
        hTxtAlgo
        hPopupDecoAlgo
        
        hPbTrain
        
        hDecoPerTxt
        hPbTrainValPer
        hPbTestPer
        hPbConfTrainTestVal
        hPbConfMatTrainVal
        hPbConfMatTest
        hPbTop2TrainVal
        hPbTop2Test
        
        hPbTest
        
        %%
        hFigTest
        
        hBgTestModel
        
        hRbOnlineTest
        
        hRbOfflineTest
        
        hTxtOfflineTestNeural
        hPbOfflineTestNeural
        
        hTxtOfflineTestBehav
        hPbOfflineTestBehav
        
        hTxtOffllineTestIndices
        hEditOffllineTestIndices
        
        hPbEvalAlgo
        
        hTxtEvalRes
        hTxtEvalResLabel
        
        
        
        
        
        
    end
    methods
        
        function hSelf=GUIBCIFW()
            %%
            figWidth=0.75;
            figHeight=0.70;
            hSelf.hFig=figure(...
                'NumberTitle','off', ...
                'Name','BCI Framework',...
                'Units','normalized', ...
                'Position',[0.05,0.2,figWidth,figHeight]);
            this(hSelf)
           
        end
        function this(hSelf)
            %%
            hSelf.hDataPnl=uipanel(...
                'Parent',hSelf.hFig, ...
                'Title','Data',...
                'FontSize',12,...
                'BackgroundColor','white', ...
                'FontWeight','bold',...
                'FontAngle','italic', ...
                'Units','normalized', ...
                'Position',[0.05,0.65,0.9,0.30]);
            
            hSelf.hTxtNeural=uicontrol(...
                'Parent', hSelf.hDataPnl, ...
                'Style','text',...
                'String','Neural File :', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.9,0.07,0.1]);
            
            hSelf.hTxtBeh=uicontrol(...
                'Parent', hSelf.hDataPnl,...
                'Style','text', ...
                'String','Behavioral File : ',...
                'Units','normalized', ...
                'Position',[0.10,0.75,0.07,0.1]);
            
            hSelf.hPbNeural= uicontrol(...
                'Parent', hSelf.hDataPnl, ...
                'Style','pushbutton', ...
                'String','Browse', ...
                'Units','normalized', ...
                'Position',[0.19,0.9,0.07,0.1]);
            
            hSelf.hPbBeh = uicontrol(...
                'Parent', hSelf.hDataPnl, ...
                'Style', 'pushbutton', ...
                'String', 'Browse', ...
                'Units', 'normalized', ...
                'Position', [0.19,0.75,0.07,0.1]);
            
            hSelf.hTxtNeuralName =uicontrol (...
                'Parent',hSelf.hDataPnl, ...
                'Style','text', ...
                'Units', 'normalized', ...
                'Position', [0.28,0.9,0.2,0.1]);
            
            hSelf.hTxtBehName = uicontrol(...
                'Parent',hSelf.hDataPnl,...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.28,0.75,0.2,0.1]);
            
            hSelf.hTxtStartOffset = uicontrol(...
                'Parent',hSelf.hDataPnl,...
                'Style', 'text', ...
                'String','Starting Offset :', ...
                'Units', 'normalized',...
                'Position' , [0.60,0.9,0.07,0.1]);
            
            hSelf.hTxtEndOffset = uicontrol(...
                'Parent',hSelf.hDataPnl,...
                'Style', 'text', ...
                'String', 'Ending Offset : ', ...
                'Units', 'normalized', ...
                'Position', [0.60,0.75, 0.07,0.1]);
            
            hSelf.hEditStartOffset =uicontrol(...
                'Parent',hSelf.hDataPnl, ...
                'Style', 'edit', ...
                'Units', 'normalized', ... 
                'Position', [0.69,0.9,0.07,0.1]);
            
            hSelf.hEditEndOffset = uicontrol(...
                'Parent',hSelf.hDataPnl, ...
                'Style', 'edit', ...
                'Units','normalized', ...
                'Position',[0.69,0.75,0.07,0.1]);
            
            
            hSelf.hTxtStartOffsetUnit=uicontrol(...
                'Parent',hSelf.hDataPnl, ...
                'Style', 'text', ...
                'String','Seconds', ...
                'Units', 'normalized', ...
                'Position', [0.78,0.9,0.07,0.1]);
            
            
            hSelf.hTxtEndOffsetUnits=uicontrol(...
                'Parent',hSelf.hDataPnl, ...
                'Style', 'text', ...
                'String','Seconds', ...
                'Units', 'normalized', ...
                'Position', [0.78,0.75,0.07,0.1]);
            
            hSelf.hTxtStartEvent=uicontrol(...
                'Parent',hSelf.hDataPnl, ...
                'Style','text', ...
                'String', 'Starting from event',...
                'Units', 'normalized', ...
                'Position',[0.28,0.52,0.1,0.1]);
            
            
            
            hSelf.hPopupStartEvent = uicontrol (...
                'Parent',hSelf.hDataPnl, ... 
                'Style', 'popup', ...
                'String',{'Inter Trial Interval ','Cue','Fixate', 'Show', ...
                'Delay', 'Act', 'Response'},...
                'Units', 'normalized', ...
                'Position', [0.39,0.52,0.1,0.1]);
            
            
            hSelf.hTxtEndEvent =uicontrol(...
                'Parent',hSelf.hDataPnl, ...
                'Style','text', ...
                'String', 'to', ...
                'Units','normalized', ...
                'Position',[0.50,0.52,0.05,0.1] );
            
            hSelf.hPopupEndEvent=uicontrol (...
                'Parent',hSelf.hDataPnl, ... 
                'Style', 'popup', ...
                'String',{'Inter Trial Interval ','Cue','Fixate', 'Show', ...
                'Delay', 'Act', 'Response'},...
                'Units', 'normalized', ...
                'Position', [0.56,0.52,0.1,0.1]);
            %%
            hSelf.hFeatExtPnl=uipanel(...
                'Parent',hSelf.hFig, ...
                'Title','Features Extraction',...
                'FontSize',12,...
                'BackgroundColor','white', ...
                'FontWeight','bold',...
                'FontAngle','italic', ...
                'Units','normalized', ...
                'Position',[0.05,0.44,0.9,0.20]);
            
            hSelf.hTxtClasses=uicontrol(...
                'Parent', hSelf.hFeatExtPnl, ...
                'Style','text',...
                'String','Target classes : ', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.85,0.1,0.1]);
            
            hSelf.hPopupClasses = uicontrol (...
                'Parent',hSelf.hFeatExtPnl, ... 
                'Style', 'popup', ...
                'String',{...
                'Rock,Paper,Scissor',...
                'Rock,Paper',...
                'Rock,Scissor', ...
                'Paper,Scissor',...
                },...
                'Units', 'normalized', ...
                'Position', [0.10,0.75,0.1,0.1]);
            
            hSelf.hTxtFeatExtOffline=uicontrol(...
                'Parent', hSelf.hFeatExtPnl, ...
                'Style','text',...
                'String','Features Extraction', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.30,0.85,0.1,0.1]);
            
            hSelf.hPopupFeatExtOffline = uicontrol (...
                'Parent',hSelf.hFeatExtPnl, ... 
                'Style', 'popup', ...
                'String',{...
                'Sorted Spikes',...
                'Unsoretd Spikes',...
                'Local Field Potential(LFP)', ...
                'Convolutional Stacked Auto-Encoders',...
                },...
                'Units', 'normalized', ...
                'Position', [0.30,0.75,0.1,0.1]);
            
            
            hSelf.hTxtFeatRedOffline =uicontrol(...
                'Parent', hSelf.hFeatExtPnl, ...
                'Style','text',...
                'String','Features Reduction', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.50,0.85,0.1,0.1]);
            
            hSelf.hPopupFeatRedOffline = uicontrol (...
                'Parent',hSelf.hFeatExtPnl, ... 
                'Style', 'popup', ...
                'String',{...
                'Principal Componenet Analysis(PCA)',...
                'Independent Component Analysis(ICA)',...
                'Restricted Boltzman Machine(RBM)', ...
                'Auto-Encoders',...
                },...
                'Units', 'normalized', ...
                'Position', [0.50,0.75,0.1,0.1]);
            
            
            hSelf.hPlotFeatRedPnl=uipanel(...
                'Parent',hSelf.hFeatExtPnl, ...
                'BackgroundColor','white', ...
                'Title','Visualize data',...
                'Position',[0.7,0.50,0.2,0.45]);
            
            
            hSelf.hPbFeatRedPlot2D=uicontrol(...
                'Parent',hSelf.hPlotFeatRedPnl,...
                'Style','pushbutton',...
                'String','2D',...
                'Units','normalize',...
                'Position',[0.05,0.2,0.40,0.6]);
            
            
            hSelf.hPbFeatRedPlot3D =   uicontrol(...
                'Parent',hSelf.hPlotFeatRedPnl,...
                'Style','pushbutton',...
                'String','3D',...
                'Units','normalize',...
                'Position',[0.50,0.2,0.40,0.6]);
            
            
            
            
            
            %%
            hSelf.hDecoPnl=uipanel(...
                'Parent',hSelf.hFig, ...
                'Title','Decoder',...
                'FontSize',12,...
                'BackgroundColor','white', ...
                'FontWeight','bold',...
                'FontAngle','italic', ...
                'Units','normalized', ...
                'Position',[0.05,0.08,0.9,0.35]);
            
            hSelf.hTxtAlgo=uicontrol(...
                'Parent', hSelf.hDecoPnl, ...
                'Style','text',...
                'String','Decoding Algorithm', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.85,0.1,0.1]);
            hSelf.hPopupDecoAlgo = uicontrol (...
                'Parent',hSelf.hDecoPnl, ... 
                'Style', 'popup', ...
                'String',{...
                'NeuralNetworks',...
                'LinearRegression',...
                'LogisticRegression', ...
                'SupportVectorMachine',...
                'RandomForest', ....
                'K-NearestNeighbours', ...
                'LinearDiscriminativeClassifier', ...
                },...
                'Units', 'normalized', ...
                'Position', [0.10,0.75,0.1,0.1]);
            
           hSelf.hPbTrain =   uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','Train',...
                'Units','normalize',...
                'Position',[0.25,0.63,0.20,0.3]);
            
            hSelf.hDecoPerTxt = uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style', 'text', ...
                'String', 'Performance', ...
                'Units', 'normalized', ...
                'Position', [0.50,0.85, 0.2,0.11]);
            
            hSelf.hPbTrainValPer = uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','TrainingValidationAccuracy',...
                'Units','normalize',...
                'Position',[0.50,0.749,0.2,0.11]);
             
            hSelf.hPbTestPer = uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','TestAccuracy',...
                'Units','normalize',...
                'Position',[0.50,0.6499,0.2,0.11]);
             
            hSelf.hPbConfTrainTestVal = uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','ConfusionMatrix',...
                'Units','normalize',...
                'Position',[0.50,0.5495,0.2,0.11]);
            
            hSelf.hPbConfMatTrainVal = uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','ConfusionMatrix(Train,Val)',...
                'Units','normalize',...
                'Position',[0.50,0.4495,0.2,0.11]);
            
            hSelf.hPbConfMatTest = uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','ConfusionMatrix(Test)',...
                'Units','normalize',...
                'Position',[0.50,0.3495,0.2,0.11]);
             
            hSelf.hPbTop2TrainVal =  uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','Top2Score(Train,Val)',...
                'Units','normalize',...
                'Position',[0.50,0.2495,0.2,0.11]);
            
            hSelf.hPbTop2Test  =  uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','Top2Score(Test)',...
                'Units','normalize',...
                'Position',[0.50,0.1495,0.2,0.11]);
            
             hSelf.hPbTest=uicontrol(...
                'Parent',hSelf.hDecoPnl,...
                'Style','pushbutton',...
                'String','Test',...
                'Units','normalize',...
                'Position',[0.75,0.63,0.20,0.3]);
            
            set(hSelf.hPbTest, 'callback', @(src, event) hPbTestCallback(hSelf, src, event));
            
            
                      
            
            
        end
        %%
        function hPbTestCallback(hSelf, src, event)
            
            figWidth=0.25;
            figHeight=0.35;
            hSelf.hFigTest=figure(...
                'NumberTitle','off', ...
                'Name','Evaluate Decoder',...
                'Units','normalized', ...
                'Position',[0.73,0.50,figWidth,figHeight]);
            thisFigTest(hSelf)
        end
        function thisFigTest(hSelf)
            hSelf.hBgTestModel= uibuttongroup(...
                'Parent',hSelf.hFigTest, ...
                'Title','Evaluation Mode', ...
                'FontSize',12,...
                'BackgroundColor','white', ...
                'FontWeight','bold',...
                'FontAngle','italic', ...
                'Units','normalized', ...
                'Position',[0.1,0.25,0.50,0.60]);
            hSelf.hRbOnlineTest = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','radiobutton',...
                'String','Online',...
                'Units','normalize',...
                'Position',[0.1,0.85,0.70,0.20]);
            
            hSelf.hRbOfflineTest = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','radiobutton',...
                'String','Offline',...
                'Units','normalize',...
                'Position',[0.1,0.50,0.70,0.20]);
            
            
            hSelf.hTxtOfflineTestNeural = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','text',...
                'String','NeuralData:',...
                'Units','normalize',...
                'Position',[0.15,0.35,0.30,0.15]);
            
            hSelf.hPbOfflineTestNeural = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','pushbutton',...
                'String','Browse',...
                'Units','normalize',...
                'Position',[0.50,0.35,0.30,0.15]);
            
            hSelf.hTxtOfflineTestBehav = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','text',...
                'String','BehavData:',...
                'Units','normalize',...
                'Position',[0.15,0.20,0.30,0.15]);
            
            hSelf.hPbOfflineTestBehav = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','pushbutton',...
                'String','Browse',...
                'Units','normalize',...
                'Position',[0.50,0.20,0.30,0.15]);
             
            hSelf.hTxtOffllineTestIndices=uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','text',...
                'String','TrialIndices:',...
                'Units','normalize',...
                'Position',[0.15,0.07,0.30,0.15]);
            
            hSelf.hEditOffllineTestIndices = uicontrol(...
                'Parent',hSelf.hBgTestModel,...
                'Style','edit',...
                'String','Session',...
                'Units','normalize',...
                'Position',[0.50,0.07,0.30,0.15]);
            
            hSelf.hPbEvalAlgo = uicontrol(...
                'Parent',hSelf.hFigTest, ...
                'Style','pushbutton', ...
                'String', 'Evaluate', ...
                'Units','normalize', ...
                'Position',[0.25,0.1,0.2,0.1]);
            
            hSelf.hTxtEvalRes = uicontrol(...
                'Parent',hSelf.hFigTest, ...
                'Style','text', ...
                'BackgroundColor', 'white', ...
                'Units','normalize', ...
                'Position',[0.70,0.5,0.2,0.1]);
            
            hSelf.hTxtEvalResLabel = uicontrol(...
                'Parent',hSelf.hFigTest, ...
                'Style','text', ...
                'String','Result', ...
                'Units','normalize', ...
                'Position',[0.70,0.6,0.2,0.1]);
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        end
    end
end