classdef GUIBCIFW2 < handle
    properties
        %%
        hFig %Parent(Canvas)
        %%
        hTabGpBCI %tabGroup: object for BCI frame work
        hTabData %tab: data
        hTabFeatExtRed%tab: Features extraction and reduction
        hTabDecoder% tab : Decoder
        %%
        %htabData: Here all the handle objects will are declared for data
        % tab
        hTxtNeuralBehav% static text:neural Data and behavioral data
        hPbNeuralBehav %pushbutton : to loadNeural and Behavioral Data file
        
        hTxtStartOffset %static text : starting offset
        hTxtEndOffset %static text : Ending offset
        hEditStartOffset % Editable text field: asking for staring offset in seconds
        hEditEndOffset  % Editable text field: asking for ending offset in seconds
        
        hTxtStartOffsetUnit %static text : unit of time is seconds
        hTxtEndOffsetUnits % static text : unit of time is second
        
        hPopupStartEvent %popup menu : starting event
        hTxtStartEvent   %text box: starting event
        hPopupEndEvent %popup menu: Ending event
        hTxtEndEvent %text box : Ending event
        
        %%
        % hTabFeatExtRed : all the handle objects will be declared for 
        hTxtClasses
        hPopupClasses
        
        hTxtFeatExtOffline
        hPopupFeatExtOffline
        
        hTxtFeatRedOffline
        hPopupFeatRedOffline
        
        hPlotFeatRedPnl
        hPbFeatRedPlot2D
        hPbFeatRedPlot3D
        
        %%
        % hTabDecoder
        hTxtDecoAlgo
        hPopupDecoAlgo
        
        hTxtParamDecoAlgo
        
        hTxtParamLayersNNC
        hEditParamLayersNNC
        
        hPbTrain
        
        hDecoPerTxt
        hPbTrainValPer
        hPbTestPer
        hPbConfTrainTestVal
        hPbConfMatTrainVal
        hPbConfMatTest
        hPbTop2TrainVal
        hPbTop2Test
        
        hPbTest
        
        %% new figure: test decoder
        hFigTest %(canvas to evaluate algo)
        
        hPopupEvalMode 
        hTxtEvalMode 
        
        hTxtDataEval%
        
        hTxtNeuralBehavDataEvalOffline %
        hPbNeuralBehavDataEvalOffline %
        hTxtTrialIndEvalOffline%
        hEditTrialIndEvalOffline%
        
        hTxtTimeStampDataEvalOnline %
        hTxtTimeStampDispDataEvalOnline%
        hTxtSystemLagDataEvalOnline%
        hTxtSytemDispDataEvalOnline%
        
        hPbExtractFeat%
        
        htxtVisualEval%
        hPbRawEcog%
        hPbRawSingleUnits%
        hPbLFPPowerSpectrum%
        hPbSortedSpikes %
        
        hPbFeatRed2D %
        hPbFeatRed3D %
        
        
        
       
        
        
        
        
    end
    methods
        function hSelf = GUIBCIFW2()
            %%
            figWidth=0.50;
            figHeight=0.50;
            hSelf.hFig=figure(...
                'NumberTitle','off', ...
                'Name','BCI Framework',...
                'Units','normalized', ...
                'Position',[0.25,0.35,figWidth,figHeight]);
            %Defining tab group
            hSelf.hTabGpBCI = uitabgroup(hSelf.hFig,'Position',[.01 .01 .9 .9]);
            
            thisData(hSelf) %Intializing all the objects of 'Data' tab
            thisFeaturesExtractionReduction(hSelf) %Initilazing all the objects of 'FeaturesExtraction&Reduction'tab 
            thisDecoder(hSelf) %Intializing all the objects of 'Decoders' tab
            
            
        end
        function thisData(hSelf)
            %%
            hSelf.hTabData = uitab('Parent', hSelf.hTabGpBCI,...
                'Title','Data',...
                'BackgroundColor','white');
           
            hSelf.hTxtNeuralBehav=uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Neural&BehavioralData:', ...
                'FontSize',10,...
                'HorizontalAlignment','center', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.25,0.80,0.22,0.07]);
            
            hSelf.hPbNeuralBehav = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','pushbutton',...
                'String','Browse', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.50,0.80,0.10,0.07]);
            
            %set(hSelf.hPbNeuralBehav, 'callback', @(src, event) hPbNeuralBehavCallback(hSelf, src, event));
            
            hSelf.hTxtStartOffset = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','StartingOffset:', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.05,0.55,0.12,0.07]);
            
            hSelf.hEditStartOffset = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','edit',...
                'String','0.0', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.19,0.55,0.10,0.07]);
            
            hSelf.hTxtStartOffsetUnit = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Seconds', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.29,0.55,0.10,0.07]);
            
            hSelf.hTxtEndOffset = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','EndingOffset:', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.50,0.55,0.12,0.07]);
            
            
            hSelf.hEditEndOffset=uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','edit',...
                'String','0.0', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.64,0.55,0.12,0.07]);
            
            hSelf.hTxtEndOffsetUnits = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Seconds', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.76,0.55,0.10,0.07]);
            
            
            
            hSelf.hTxtStartEvent = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','Starting from Event', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.22,0.30,0.20,0.07]);
            
            
            hSelf.hPopupStartEvent = uicontrol (...
                'Parent',hSelf.hTabData, ... 
                'Style', 'popup', ...
                'FontSize',10,...
                'String',{'Inter Trial Interval ','Cue','Fixate', 'Show', ...
                'Delay', 'Act', 'Response'},...
                'Units', 'normalized', ...
                'Position', [0.43,0.27,0.1,0.1]);
            
            hSelf.hTxtEndEvent = uicontrol(...
                'Parent', hSelf.hTabData, ...
                'Style','text',...
                'String','to', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.54,0.30,0.07,0.07]);
            
            hSelf.hPopupEndEvent = uicontrol (...
                'Parent',hSelf.hTabData, ...
                'Style', 'popup', ...
                'FontSize',10,...
                'String',{'Inter Trial Interval ','Cue','Fixate', 'Show', ...
                'Delay', 'Act', 'Response'},...
                'Units', 'normalized', ...
                'Position', [0.62,0.27,0.1,0.1]);                                             
            
        end
              
        
        
        function thisFeaturesExtractionReduction(hSelf)
            %%
            %Defining the object for tab FeaturesExtraction&Reduction: 
            hSelf.hTabFeatExtRed = uitab(...
                'Parent',hSelf.hTabGpBCI,...
                'Title','FeaturesExtraction&Redcution',...
                'BackgroundColor','white');
            %Now start populating the tab by different required objects:
            hSelf.hTxtClasses = uicontrol(...
                'Parent', hSelf.hTabFeatExtRed, ...
                'Style','text',...
                'String','Classes', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.1,0.8,0.15,0.07]);
            
            hSelf.hPopupClasses = uicontrol (...
                'Parent',hSelf.hTabFeatExtRed, ... 
                'Style', 'popup', ...
                'String',{...
                'Rock,Paper,Scissor',...
                'Rock,Paper',...
                'Rock,Scissor', ...
                'Paper,Scissor',...
                },...
                'Units', 'normalized', ...
                'Position', [0.1,0.72,0.15,0.1]);
            
            
            hSelf.hTxtFeatExtOffline = uicontrol(...
                'Parent', hSelf.hTabFeatExtRed, ...
                'Style','text',...
                'String','FeaturesExtraction', ...
                'FontSize',10,...
                'units','normalized', ...
                'Position', [0.30,0.8,0.15,0.07]);
            
            hSelf.hPopupFeatExtOffline = uicontrol (...
                'Parent',hSelf.hTabFeatExtRed, ... 
                'Style', 'popup', ...
                'String',{...
                'Sorted Spikes',...
                'Unsoretd Spikes',...
                'Local Field Potential(LFP)', ...
                'Convolutional Stacked Auto-Encoders',...
                },...
                'Units', 'normalized', ...
                'Position', [0.30,0.72,0.15,0.1]);
            
            hSelf.hTxtFeatRedOffline = uicontrol(...
                'Parent', hSelf.hTabFeatExtRed, ...
                'Style','text',...
                'FontSize',10,...
                'String','FeaturesReduction', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.50,0.80,0.15,0.07]);
            
            hSelf.hPopupFeatRedOffline =  uicontrol (...
                'Parent',hSelf.hTabFeatExtRed, ... 
                'Style', 'popup', ...
                'String',{...
                'Principal Componenet Analysis(PCA)',...
                'Independent Component Analysis(ICA)',...
                'Restricted Boltzman Machine(RBM)', ...
                'Auto-Encoders',...
                },...
                'Units', 'normalized', ...
                'Position', [0.50,0.72,0.15,0.1]);
            
            hSelf.hPlotFeatRedPnl=uipanel(...
                'Parent',hSelf.hTabFeatExtRed, ...
                'BackgroundColor','white', ...
                'FontSize',10,...
                'Title','Visualize Data',...
                'Position',[0.7,0.63,0.2,0.25]);
            
            hSelf.hPbFeatRedPlot2D=uicontrol(...
                'Parent',hSelf.hPlotFeatRedPnl,...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','2D',...
                'Units','normalize',...
                'Position',[0.05,0.35,0.40,0.40]);
            
            hSelf.hPbFeatRedPlot3D =   uicontrol(...
                'Parent',hSelf.hPlotFeatRedPnl,...
                'Style','pushbutton',...
                'String','3D',...
                'Units','normalize',...
                'Position',[0.50,0.35,0.40,0.40]);
                  
            
        end
        
        function thisDecoder(hSelf)
            %%
            hSelf.hTabDecoder = uitab(...
                'Parent',hSelf.hTabGpBCI,...
                'Title','Decoder',...
                'BackgroundColor','white');
            
            hSelf.hTxtDecoAlgo=uicontrol(...
                'Parent', hSelf.hTabDecoder, ...
                'Style','text',...
                'FontSize',10,...
                'String','Decoding Algorithms', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.10,0.80,0.20,0.07]);
            
            hSelf.hPopupDecoAlgo = uicontrol (...
                'Parent',hSelf.hTabDecoder, ... 
                'Style', 'popup', ...
                'String',{...
                'NeuralNetworks',...
                'LinearRegression',...
                'LogisticRegression', ...
                'SupportVectorMachine',...
                'RandomForest', ....
                'K-NearestNeighbours', ...
                'LinearDiscriminativeClassifier', ...
                },...
                'Units', 'normalized', ...
                'Position', [0.10,0.75,0.20,0.07]);
            
            set(hSelf.hPopupDecoAlgo, 'callback', @(src, event) hPopupDecoAlgoCallback(hSelf, src, event));
            
            
            hSelf.hTxtParamDecoAlgo =uicontrol(...
                'Parent', hSelf.hTabDecoder, ...
                'Style','text',...
                'FontSize',10,...
                'String','Parameters', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.40,0.80,0.20,0.07]);
            
            
            hSelf.hTxtParamLayersNNC =uicontrol(...
                'Parent', hSelf.hTabDecoder, ...
                'Visible','off', ...
                'Style','text',...
                'FontSize',10,...
                'String','layers', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.40,0.75,0.10,0.07]);
            
            hSelf.hEditParamLayersNNC =  uicontrol(...
                'Parent', hSelf.hTabDecoder, ...
                'Visible','off', ...
                'Style','edit',...
                'FontSize',10,...
                'String','[  ]', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.50,0.75,0.10,0.07]);
            
                     
            
            
            hSelf.hPbTrain =   uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'FontSize',10,...
                'String','Train',...
                'Units','normalize',...
                'Position',[0.75,0.75,0.15,0.1]);
            
            hSelf.hDecoPerTxt = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style', 'text', ...
                'String', 'Performance', ...
                'FontSize',10,...
                'Units', 'normalized', ...
                'Position', [0.40,0.50, 0.2,0.07]);
            
            hSelf.hPbTrainValPer = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','TrainingValidationAccuracy',...
                'Units','normalize',...
                'Position',[0.40,0.431,0.2,0.07]);
            
            hSelf.hPbTestPer = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','TestAccuracy',...
                'Units','normalize',...
                'Position',[0.40,0.369,0.2,0.07]);
            
             hSelf.hPbConfTrainTestVal = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','ConfusionMatrix',...
                'Units','normalize',...
                'Position',[0.40,0.308,0.2,0.07]);
            
            hSelf.hPbConfMatTrainVal = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','ConfusionMatrix(Train,Val)',...
                'Units','normalize',...
                'Position',[0.40,0.247,0.2,0.07]);
            
            hSelf.hPbConfMatTest = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','ConfusionMatrix(Test)',...
                'Units','normalize',...
                'Position',[0.40,0.188,0.2,0.07]);
            
            hSelf.hPbTop2TrainVal =  uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','Top2Score(Train,Val)',...
                'Units','normalize',...
                'Position',[0.40,0.13,0.2,0.07]);
            
            hSelf.hPbTop2Test=uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','Top2Score(Test)',...
                'Units','normalize',...
                'Position',[0.40,0.07,0.2,0.07]);
            
            
            hSelf.hPbTest = uicontrol(...
                'Parent',hSelf.hTabDecoder,...
                'Style','pushbutton',...
                'String','Test',...
                'Units','normalize',...
                'Position',[0.75,0.25,0.15,0.1]);
            
            set(hSelf.hPbTest, 'callback', @(src, event) hPbTestCallback(hSelf, src, event));
            
            
        end
        
          function thisFigTest(hSelf)
            
            
            hSelf.hTxtEvalMode =uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','text',...
                'FontSize',10,...
                'String','EvaluationMode', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.1,0.80,0.20,0.07]);
            
            
            hSelf.hPopupEvalMode = uicontrol (...
                'Parent',hSelf.hFigTest, ... 
                'Style', 'popup', ...
                'String',{...
                'Online', ...
                'Offline',...
                },...
                'Units', 'normalized', ...
                'BackgroundColor','white', ...
                'Position', [0.10,0.75,0.20,0.07]);
            set(hSelf.hPopupEvalMode, 'callback', @(src, event) hPopupEvalModeCallback(hSelf, src, event));
            
            
            hSelf.hTxtDataEval = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','text',...
                'FontSize',10,...
                'String','Data', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.80,0.20,0.07]);
            
            hSelf.hTxtNeuralBehavDataEvalOffline= uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','text',...
                'String','Neural&BehavData', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.40,0.75,0.15,0.07]);
            
            hSelf.hPbNeuralBehavDataEvalOffline = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','pushbutton',...
                'String','Browse', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.55,0.75,0.15,0.07]);
            
            hSelf.hTxtTrialIndEvalOffline = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','text',...
                'Visible','off', ...
                'String','Trial Indices', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.40,0.681,0.15,0.07]);
                
            hSelf.hEditTrialIndEvalOffline =uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','edit',...
                'String','[session]', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.55,0.681,0.15,0.07]);
            
            hSelf.hTxtTimeStampDataEvalOnline = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','text',...
                'String','NSPTimeStamp', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.40,0.75,0.15,0.07]);
            
            hSelf.hTxtTimeStampDispDataEvalOnline = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','text',...
                'String','123456', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.55,0.75,0.15,0.07]);
            
            
            hSelf.hTxtSystemLagDataEvalOnline = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','text',...
                'String','SytemLag', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.40,0.681,0.15,0.07]);
            
            hSelf.hTxtSytemDispDataEvalOnline = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','off', ...
                'Style','text',...
                'String','0.001', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'BackgroundColor','white', ...
                'Position', [0.55,0.681,0.15,0.07]);
            
            
            hSelf.hPbExtractFeat = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Visible','on', ...
                'Style','pushbutton',...
                'String','ExtractFeatures', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.1,0.55,0.15,0.07]);
            
            hSelf.htxtVisualEval = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','text',...
                'FontSize',10,...
                'String','VisualizeData', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.55,0.20,0.07]);
            
            hSelf.hPbRawEcog =  uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','pushbutton',...
                'String','EcogSignal', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.53,0.20,0.07]);
            
            
            hSelf.hPbRawSingleUnits = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','pushbutton',...
                'String','SingleUnitsActivity', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.47,0.20,0.07]);
            
            
            hSelf.hPbLFPPowerSpectrum = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','pushbutton',...
                'String','PowerSpectrum', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.41,0.20,0.07]);
            
            hSelf.hPbSortedSpikes = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','pushbutton',...
                'String','SortedUnits', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.343,0.20,0.07]);
            
            hSelf.hPbFeatRed2D = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','pushbutton',...
                'String','FeaturesReduction-2D', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.276,0.20,0.07]);
            
            hSelf.hPbFeatRed3D = uicontrol(...
                'Parent', hSelf.hFigTest, ...
                'Style','pushbutton',...
                'String','FeaturesReduction-3D', ...
                'units','normalized', ...
                'HorizontalAlignment','center', ...
                'Position', [0.45,0.219,0.20,0.07]);
            
            
            
            
        
            
    
            
                     
            
        end
        
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%%%%%%%%%%%%%%% Callbacks(Decoders Tab) %%%%%%%%%%%%%%%%%%%%
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
        function hPopupDecoAlgoCallback(hSelf, src, event)
          %calling the static function of  class 
          CallbacksGUIBCIFW2.hPopupDecoAlgoCallback(hSelf)
            
        end
        
        function hPbTestCallback(hSelf, src, event)
            figWidth=0.40;
            figHeight=0.60;
            hSelf.hFigTest=figure(...
                'NumberTitle','off', ...
                'Name','Evaluate Decoder',...
                'Units','normalized', ...
                'Position',[0.50,0.30,figWidth,figHeight]);
            thisFigTest(hSelf)   
        end
        
        function hPopupEvalModeCallback(hSelf, src, event)
            CallbacksGUIBCIFW2.hPopupEvalModeCallback(hSelf)
        end
      
        
        
        

    end
end